# -*- coding: utf-8 -*-
"""Batch image 4 ver2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XiWfLkAJU7oVStZRwm6ef-ce_njQdwZi
"""

from PIL import Image
import requests
from io import BytesIO
import zipfile
import os
import pandas as pd

# Load ảnh từ URL
def load_image_from_url(url):
    response = requests.get(url)
    return Image.open(BytesIO(response.content)).convert("RGBA")

# Resize ảnh đúng kích thước card
def resize_card(img, width=210, height=336):
    return img.resize((width, height), Image.LANCZOS)

# Ghép 4 ảnh lại thành 1 ảnh 410x336 theo tên tùy chỉnh
def merge_four_images(urls, output_name):
    card_width, card_height = 210, 336
    output_width, output_height = 410, 336


    img_A = resize_card(load_image_from_url(urls[0]))
    img_B = resize_card(load_image_from_url(urls[1]))
    img_C = resize_card(load_image_from_url(urls[2]))
    img_D = resize_card(load_image_from_url(urls[3]))

    canvas = Image.new("RGBA", (output_width, output_height), (0, 0, 0, 0))
    x_A = 0             # 0
    x_B = x_A + 60              # 60
    x_C = x_B + 70              # 130
    x_D = x_C + 70              # 200


    canvas.paste(img_D, (x_D, 0), img_D)
    canvas.paste(img_C, (x_C, 0), img_C)
    canvas.paste(img_B, (x_B, 0), img_B)
    canvas.paste(img_A, (x_A, 0), img_A)

    filename = f"{output_name}.png"
    canvas.save(filename)
    return filename

# === Dành cho Google Colab ===
# B1: Tải file CSV lên trước (2 cột: tên, url)
from google.colab import files
uploaded = files.upload()

# B2: Đọc file CSV
csv_filename = list(uploaded.keys())[0]
df = pd.read_csv(csv_filename)

# B3: Kiểm tra định dạng và nhóm 4 dòng/ảnh
if len(df) % 4 != 0:
    raise ValueError("Số lượng dòng trong file CSV phải chia hết cho 4.")
if df.shape[1] < 2:
    raise ValueError("File CSV phải có ít nhất 2 cột: tên và url")

result_files = []
for i in range(0, len(df), 4):
    group = df.iloc[i:i+4]
    name = str(group.iloc[0, 0])  # tên ảnh lấy từ dòng đầu tiên của nhóm
    urls = group.iloc[:, 1].tolist()
    result_file = merge_four_images(urls, name)
    result_files.append(result_file)

# B4: Nén các file PNG vào 1 file ZIP
zip_filename = "merged_images_named.zip"
with zipfile.ZipFile(zip_filename, 'w') as zipf:
    for file in result_files:
        zipf.write(file)

# B5: Cho phép tải về file zip
files.download(zip_filename)

# Cleanup (tuỳ chọn)
# for file in result_files:
#     os.remove(file)
# os.remove(zip_filename)